services:
  proxy:
    container_name: app-name-proxy
    image: nginx:mainline-alpine3.21-slim
    ports:
      - 3500:80
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - internal
    depends_on:
      - php
      # - mariadb

  php:
    container_name: app-name-php
    build: './docker/php'
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - internal
#     depends_on:
#       - mariadb

#   phpmyadmin:
#     container_name: app-name-phpmyadmin
#     image: phpmyadmin/phpmyadmin:latest
#     ports:
#       - 8000:80
#     environment:
#       - PMA_ARBITRARY=1
#       - PMA_HOST=mariadb
#     networks:
#       - internal
#     depends_on:
#       - mariadb

#   mariadb:
#     container_name: app-name-mariadb
#     image: mariadb:latest
#     restart: always
#     volumes:
#       - app-name-mariadb-data:/var/lib/mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: DevelopmentPassword
#     networks:
#       - internal

# volumes:
#   wt-mariadb-data:


networks:
  internal:
    driver: bridge
